// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Template.Database.Logs.DbContexts.SQLite;

#nullable disable

namespace Template.Database.Logs.DbContexts.SQLite.Migrations
{
    [DbContext(typeof(LogDBContext_SQLite))]
    [Migration("20221204195818_InitialMigrations")]
    partial class InitialMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Template.Database.Logs.DbContexts.Base.Models.LogMessageEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("DateTimeOffset")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ThreadId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LogMessageEntity");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DateTimeOffset = new DateTimeOffset(new DateTime(2022, 12, 4, 19, 58, 18, 222, DateTimeKind.Unspecified).AddTicks(6946), new TimeSpan(0, 0, 0, 0, 0)),
                            LogLevel = "Information",
                            Message = "First Message",
                            ThreadId = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
